name: Scan docker images
on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string
      target_tag_postfix:
        required: false
        default: ''
        type: string

jobs:
  security:
    name: Security scan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - base
          - aws
          - gcp
          - azure
        platform:
          - linux/amd64
          - linux/arm64
        versions: ${{ fromJson(inputs.matrix) }}
    steps:
      - name: Prepare
        env:
          TARGET_TAG: -${{ matrix.target }}${{ inputs.target_tag_postfix }}
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
          if [[ "${TARGET_TAG}" == "-base" ]]; then
            TARGET_TAG=""${{ inputs.target_tag_postfix }}
          fi
          echo "TARGET_TAG=${TARGET_TAG}" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scanner for ${{ matrix.target }} image
        uses: aquasecurity/trivy-action@0.27.0
        with:
          image-ref: "ghcr.io/${{ github.repository }}:${{ matrix.versions.ansible }}${{ env.TARGET_TAG }}-${{ env.PLATFORM_PAIR }}"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "${{ matrix.target }}${{ inputs.target_tag_postfix }}.sarif"
          severity: "CRITICAL,HIGH"
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db

      - name: Upload ${{ matrix.target }}${{ inputs.target_tag_postfix }} image scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: ${{ matrix.target }}${{ inputs.target_tag_postfix }}
          sarif_file: "${{ matrix.target }}${{ inputs.target_tag_postfix }}.sarif"

