name: Scan docker images
on:
  workflow_call:
    inputs:
      versions:
        required: true
        type: string
      base_image:
        required: true
        type: string

jobs:
  security:
    name: Security scan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - base
          - aws
          - gcp
          - azure
        platform:
          - linux/amd64
          - linux/arm64
        base_image:
          - name: ${{ inputs.base_image }}
            tag_suffix: ""
          - name: python:3.11-alpine
            tag_suffix: "-python-3.11"
          - name: spacelift-io/alpine-fips:python-latest
            tag_suffix: "-fips"
        versions: ${{ fromJson(inputs.versions) }}
    steps:
      - name: Prepare
        env:
          TARGET_TAG: -${{ matrix.target }}${{ matrix.base_image.tag_suffix }}
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
          if [[ "${TARGET_TAG}" == "-base" ]]; then
            TARGET_TAG=""
          fi
          echo "TARGET_TAG=${TARGET_TAG}" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scanner for ${{ matrix.target }} image
        uses: aquasecurity/trivy-action@0.27.0
        with:
          image-ref: "ghcr.io/${{ github.repository }}:${{ matrix.versions.ansible }}${{ env.TARGET_TAG }}-${{ env.PLATFORM_PAIR }}"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "${{ matrix.target }}${{ matrix.base_image.tag_suffix }}.sarif"
          severity: "CRITICAL,HIGH"
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db

      - name: Upload ${{ matrix.target }}${{ matrix.base_image.tag_suffix }} image scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: ${{ matrix.target }}${{ matrix.base_image.tag_suffix }}
          sarif_file: "${{ matrix.target }}${{ matrix.base_image.tag_suffix }}.sarif"

